# Generated by Django 5.1.3 on 2025-05-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextdoor', '0003_remove_club_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nextdoor.club'),
            preserve_default=False,
        ),
    ]
